#include_recipe "pivotal_workstation::rvm"
include_recipe "pivotal_workstation::git_scripts"
include_recipe "pivotal_workstation::chrome"
include_recipe "pivotal_workstation::homebrew"
include_recipe "pivotal_workstation::gitx"
include_recipe "pivotal_workstation::sshd_on"
include_recipe "pivotal_workstation::screen_sharing_on"
include_recipe "pivotal_workstation::postgres"
include_recipe "pivotal_workstation::gem_no_rdoc_no_ri"
include_recipe "pivotal_workstation::rubymine"
include_recipe "pivotal_workstation::skype"
include_recipe "pivotal_workstation::size_up"
include_recipe "pivotal_workstation::imagemagick"
include_recipe "pivotal_workstation::set_screensaver_preferences"
include_recipe "pivotal_workstation::firefox"
##include_recipe "pivotal_workstation::mysql"  # broken
