include_recipe "pivotal_workstation::homebrew"
include_recipe "pivotal_workstation::ack"

brew_install "watch"
brew_install "ssh-copy-id"
brew_install "pstree"
brew_install "tmux"
brew_install "tree"
brew_install "wget"
brew_install "proctools"
