include_recipe "homebrew"
include_recipe "pivotal_workstation::ack"
include_recipe "pivotal_workstation::tmux"
include_recipe "pivotal_workstation::xquartz"

package "watch"
package "ssh-copy-id"
package "pstree"
package "tree"
package "wget"
