#! /usr/bin/env ruby
require "rubygems"
require "bundler"
Bundler.setup

require "json"

log_level = ENV['LOG_LEVEL'] || "info"

json_file = "chef/workstation.json"

if ARGV.length >= 1
  json_config = JSON.parse(File.read(json_file))
  json_config["recipes"] = ARGV
  json_file = "/tmp/#{File.basename(json_file)}"
  puts "OVERRIDING RECIPES: running [#{json_config["recipes"].join(", ")}].  Temp json config file: #{json_file}"
  File.open(json_file, "w+"){|f| f<<JSON.pretty_generate(json_config) }
end

command = "sudo bundle exec chef-solo -j #{json_file} -c solo.rb -l #{log_level}"
puts "running chef: " + command
system(command) || exit(1)